name: shilindongxing
on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shilindongxing
        env:
          frc1: ${{ secrets.frc1 }}
        run: |
          echo $frc1 | jq -r .l27 | /bin/bash
          echo $tjin670 | jq -r .j5904 | /bin/bash
          echo $waknh0261 | jq -r .kfn754 | /bin/bash
          echo $dicw03 | jq -r .gtmm7511 | /bin/bash

